[profile.default]
src = "src"
out = "out"
no_match_test = "test/MarketplacePenetrationTests.t.sol"
libs = ["lib"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
